const CracoAntDesignPlugin = require('craco-antd')

module.exports = {
  plugins: [
    {
      plugin: CracoAntDesignPlugin,
      options: {
        customizeTheme: {
          '@font-family': 'Dana !important',
          '@blue-base': '#0c67f0',
          '@primary-color': '#04b946',
          '@success-color': '#04b946',
          '@error-color': '#dd0a0a',
          '@warning-color': '#ffb60a',
          '@black': '#404040',
          '@font-size-base': '16px',
          '@text-color': '#404040',
          '@link-color': '#04b946',
          '@disabled-color': '#9c9c9c',
          '@highlight-color': '#eefff2',
          '@body-background': '#f9f9f9',
          '@modal-mask-bg': 'fade(#404040, 40%)',
          '@box-shadow-base': ' 0 3px 10px 0 rgba(64, 64, 64, 0.16)',
          '@modal-header-padding': '24px',
          '@modal-footer-padding-vertical': '24px',
          '@modal-footer-padding-horizontal': '24px',
          '@btn-default-color': '#404040',
          '@btn-default-border': '#04b946',
          '@disabled-color': '#dedede',
          '@disabled-bg': '#f9f9f9',
          '@breadcrumb-base-color': '#404040',
          '@breadcrumb-font-size': '14px',
          '@breadcrumb-link-color': '#404040',
          '@breadcrumb-separator-color': '#404040',
          '@menu-item-color': '#404040',
          '@line-height-base': '1.5',
          '@btn-font-weight': '500',
          '@btn-font-size-lg': '16px',
          '@btn-font-size-sm': '16px',
          '@btn-padding-horizontal-base': '24px',
          '@btn-padding-horizontal-lg': '40px',
          '@btn-padding-horizontal-sm': '8px',
          '@btn-height-base': '40px',
          '@btn-height-lg': '56px',
          '@btn-height-sm': '32px',
          '@skeleton-paragraph-margin-top': '12px',
          '@skeleton-paragraph-li-margin-top': '12px',
          '@skeleton-paragraph-li-height': '24px',
          '@skeleton-title-height': '24px',
          '@skeleton-title-paragraph-margin-top': '16px',
        },
      },
    },
  ],
}
