export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const RESET_ALL_DATA = 'RESET_ALL_DATA'

export const FETCH_ACTIVE_DATA_SUCCESS = 'FETCH_ACTIVE_DATA_SUCCESS'
export const FETCH_ACTIVE_DATA_FAILURE = 'FETCH_ACTIVE_DATA_FAILURE'
export const FETCH_ACTIVE_DATA_REQUEST = 'FETCH_ACTIVE_DATA_REQUEST'
export const RESET_ALL_ACTIVE_DATA = 'RESET_ALL_ACTIVE_DATA'

export const FETCH_DEACTIVATE_DATA_SUCCESS = 'FETCH_DEACTIVATE_DATA_SUCCESS'
export const FETCH_DEACTIVATE_DATA_FAILURE = 'FETCH_DEACTIVATE_DATA_FAILURE'
export const FETCH_DEACTIVATE_DATA_REQUEST = 'FETCH_DEACTIVATE_DATA_REQUEST'
export const RESET_ALL_DEACTIVATE_DATA = 'RESET_ALL_DEACTIVATE_DATA'
